version: "3"

services:
  # front-end:
  #   container_name: front-end
  #   build:
  #     context: ./client/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api/api-gateway/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./api/api-gateway:/app
    env_file:
      - .env  

  user-service:
    container_name: user-service
    build:
      context: ./api/user-service/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      mongodb:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./api/user-service:/app
    env_file:
      - .env

  question-service:
    container_name: question-service
    build:
      context: ./api/question-service/
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./api/question-service:/app
    env_file:
      - .env

  matching-service:
    container_name: matching-service
    build:
      context: ./api/matching-service/
      dockerfile: Dockerfile
    ports:
      - 8300:8300
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./api/matching-service:/app
    env_file:
      - .env

  matchmaking-service:
    container_name: matchmaking-service
    build:
      context: ./api/matchmaking-service/
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./api/matchmaking-service:/app
    env_file:
      - .env

  communication-service:
    container_name: communication-service
    build:
      context: ./api/communication-service/
      dockerfile: Dockerfile
    ports:
      - 8400:8400
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./api/communication-service:/app
    env_file:
      - .env

  collaboration-socket:
    container_name: collaboration-socket
    build:
      context: ./socket/collaboration-socket
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ./socket/collaboration-socket:/app
    env_file:
      - .env

  communication-socket:
    container_name: communication-socket
    build:
      context: ./socket/communication-socket
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    volumes:
      - ./socket/communication-socket:/app
    env_file:
      - .env      
      
  mysql:
    image: mysql
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: peerprep
    volumes:
      - user-service-db-data:/var/lib/mysql/
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb-db-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "pgrep mongod"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3

volumes:
  user-service-db-data:
  question-service-db-data:     