version: "3"

services:
  front-end:
    container_name: front-end
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules  

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api/api-gateway/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    volumes:
      - ./api/api-gateway:/app
      - /app/node_modules
    env_file:
      - .env  

  user-service:
    container_name: user-service
    build:
      context: ./api/user-service/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - mysql  
    volumes:
      - ./api/user-service:/app
      - /app/node_modules
    env_file:
      - .env

  question-service:
    container_name: question-service
    build:
      context: ./api/question-service/
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    depends_on:
      - mongodb
    volumes:
      - ./api/question-service:/app
      - /app/node_modules
    env_file:
      - .env

  mysql:
    image: mysql
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: peerprep
    volumes:
      - user-service-db-data:/var/lib/mysql/
    ports:
      - "3307:3306"

  mongodb:
    image: mongo
    restart: always
    volumes:
      - question-service-db-data:/data/db
    ports:
      - "27017:27017"

volumes:
  user-service-db-data:
  question-service-db-data:     