version: "3"

services:
  front-end:
    container_name: front-end
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - default

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api/api-gateway/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./api/api-gateway:/app
    env_file:
      - .env 
    networks:
      - default

  user-service:
    container_name: user-service
    build:
      context: ./api/user-service/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      mongodb:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - ./api/user-service:/app
    env_file:
      - .env
    networks:
      - default 

  question-service:
    container_name: question-service
    build:
      context: ./api/question-service/
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./api/question-service:/app
    env_file:
      - .env
    networks:
      - default

  matching-service:
    container_name: matching-service
    build:
      context: ./api/matching-service/
      dockerfile: Dockerfile
    ports:
      - 8300:8300
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./api/matching-service:/app
    env_file:
      - .env
    networks:
      - default

  matchmaking-service:
    container_name: matchmaking-service
    build:
      context: ./api/matchmaking-service/
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./api/matchmaking-service:/app
    env_file:
      - .env
    networks:
      - default

  mysql:
    image: mysql
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: peerprep
    volumes:
      - user-service-db-data:/var/lib/mysql/
      - ./api/user-service/dump:/dump
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - default

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb-db-data:/data/db
      - ./api/question-service/dump:/data/dump
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "pgrep mongod"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - default

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - default

volumes:
  user-service-db-data:
  mongodb-db-data:     

networks:
  default:
    name: peerprep-network

  
